class SearchableNames

  def self.test_names
    %w(Carioca)
  end

  def self.portugual
    %w( Abreu
        Acosta
        Afonso
        Agre
        Almada
        Almeda
        Almeida
        Alto
        Alva
        Alvarenga
        Alvares
        Alvernaz
        Alves
        Amaral
        Amorim
        Anes
        Antunes
        Aparicio
        Araujo
        Armao
        Arruda
        Arvelo
        Avelar
        Avila
        Avilla
        Azevedo
        Barbas
        Barbosa
        Barboza
        Barcellos
        Baros
        Barreto
        Basto
        Bastos
        Belo
        Bento
        Bomba
        Borba
        Borges
        Botelho
        Braga
        Branco
        Brandao
        Brasil
        Braz
        Brito
        Broas
        Cabral
        Cacho
        Caetano
        Cal
        Caldeira
        Camacho
        Camara
        Campos
        Candido
        Caravalho
        Cardoso
        Cardoza
        Carias
        Carneiro
        Carreira
        Carreiro
        Carrico
        Carris
        Carvalho
        Cassis
        Castelo
        Cavaco
        Cerqueira
        Chao
        Chaves
        Chaves
        Chavis
        Chico
        Claudio
        Coelho
        Conceicao
        Constancio
        Corado
        Cordeiro
        Correia
        Costa
        Costa
        Costas
        Cotta
        Coutinho
        Couto
        Coval
        Criado
        Cuba
        Cunha
        Curro
        D’Souza
        DaCosta
        DaCruz
        DaCunha
        DaLuz
        DaRocha
        DaRosa
        DaSilva
        Damaso
        Danca
        DeAraujo
        DeArmas
        DeBarros
        DeCarvalho
        DeCotis
        DeFreitas
        DeJulio
        DeLacerda
        DeLemos
        DeLima
        DeMello
        DeMelo
        DeMoura
        DeOliveira
        DePina
        DeSa
        DeSousa
        DeSouza
        Deus
        Dias
        Diniz
        Domingos
        Domingues
        Dorta
        DosSantos
        Duarte
        Dutra
        Eanes
        Enes
        Ennes
        Espindola
        Espinola
        Estacio
        Esteves
        Evora
        Fagundes
        Faria
        Farias
        Farinha
        Fernandes
        Ferra
        Festa
        Fidalgo
        Fiel
        Figueira
        Figueiredo
        Flor
        Fogo
        Fonte
        Fontes
        Formosa
        Formoso
        Fortes
        Fosco
        Franca
        Frasco
        Frausto
        Freire
        Freitas
        Furtado
        Gaia
        Gale
        Galioto
        Gama
        Gandara
        Garro
        Goes
        Gomes
        Goncalves
        Gouveia
        Graca
        Guardado
        Guedes
        Guerreiro
        Guimaraes
        Gularte
        Henriques
        Hilario
        Hiza
        Ines
        Janota
        Jeronimo
        Joaquim
        Judice
        Junior
        Lacerda
        Lage
        Lapa
        Leitao
        Leite
        Lessa
        Lias
        Lima
        Limas
        Linhares
        Lois
        Lomba
        Pagination
        Lopes
        Loureiro
        Lourenco
        Louro
        Lucio
        Luis
        Luiz
        Macedo
        Maciel
        Madeira
        Madeiros
        Maestre
        Magalhaes
        Maia
        Mangual
        Marcelino
        Marcelo
        Marques
        Marroquin
        Marte
        Martha
        Martines
        Martinho
        Martins
        Mascarenhas
        Mata
        Mateus
        Matheus
        Matos
        Mattos
        Mau
        Mauricio
        Medeiros
        Mello
        Melo
        Mendes
        Mendonca
        Meneses
        Menezes
        Merenda
        Mesquita
        Migues
        Miguez
        Mina
        Mirante
        Monge
        Moniz
        Monserrate
        Montalto
        Montalvo
        Monteiro
        Monterroso
        Montez
        Mora
        Moraes
        Morais
        Moreira
        Morgado
        Motta
        Moura
        Muniz
        Narciso
        Nascimento
        Natal
        Naves
        Nazario
        Neto
        Netto
        Neve
        Neves
        Neves
        Nicolau
        Nobrega
        Nobriga
        Nogueira
        Nolasco
        Nora
        Noronha
        Novo
        Nunes
        Oliveira
        Ornelas
        Ornellas
        Orta
        Osorio
        Paes
        Pais
        Paiva
        Palma
        Pao
        Parente
        Parreira
        Paula
        Paulino
        Paulo
        Paulos
        Pavao
        Peixoto
        Penso
        Pereira
        Pagination
        Peres
        Pereyra
        Perna
        Pero
        Perreira
        Peru
        Pesqueira
        Pestana
        Pimenta
        Pimental
        Pimentel
        Pinheiro
        Pinho
        Pinto
        Pires
        Po
        Pombo
        Ponte
        Pontes
        Porro
        Portela
        Porto
        Prata
        Primo
        Prior
        Quadros
        Quintal
        Quintela
        Rama
        Ramalho
        Ramires
        Ramires
        Ramos
        Rapa
        Raposa
        Raposa
        Raposo
        Rapoza
        Rapozo
        Raso
        Rebelo
        Regalado
        Rego
        Reis
        Reposa
        Resendes
        Reveles
        Reza
        Rezendes
        Ribeiro
        Rocha
        Rodarte
        Rodrigues
        Rodriques
        Rosa
        Ruelas
        Ruis
        Sa
        Saade
        Sabina
        Sago
        Sales
        Sales
        Sampaio
        Sanches
        Santa
        Saraiva
        Sardinha
        Sarmento
        Seda
        Sena
        Sequeira
        Sereno
        Serpa
        Serrao
        Silva
        Silvas
        Simao
        Simas
        Simoes
        Soares
        Socia
        Sola
        Solorio
        Sousa
        Souto
        Souva
        Souza
        Spinola
        Tavares
        Teixeira
        Telles
        Teves
        Texeira
        Trindade
        Troia
        Vala
        Vara
        Vas
        Vasconcelos
        Vaz
        Veiga
        Vela
        Velez
        Velo
        Veloso
        Veloso
        Vento
        Verissimo
        Viana
        Viegas
        Vieyra
        Villela
        Villella
        Xavier)
  end

  def self.brazilian_last_names
    %w(Almeida
      Alsina
      Alves
      Amado
      Andrade
      Azevedo
      Baia
      Barbosa
      Braga
      Cabreira
      Caetano
      Cardoso
      Carvalho
      Coelho
      Conceicao
      Cunha
      DaCosta
      DaSilva
      D'Almeida
      DeCarvalho
      DeFreitas
      DeOliveira
      DePaulo
      DeSousa
      DeSouza
      DosSantos
      Freitas
      Guimaraes
      Joao
      Magalhaes
      Martins
      Medeiros
      Morais
      Moreira
      Nascimento
      Nogueira
      Oliveira
      Paixao
      Pereira
      Pinheiro
      Pinto
      Ribeiro
      Rocha
      Salgueiro
      Sardinha
      Simoes
      Siqueira
      Souza
      Teixeira
      Vieira)
  end

  def self.angolan_last_names
    %w(
        Lanzi
        Lelo
        Liberal
        Lito
        Livramento
        Lomba
        Luisa
        Mangueira
        Manuel
        Maravilha
        Margarida
        Marinela
        Mario
        Marlene
        Marley
        Massano
        Mazon
        Meno
        Micolo
        Mimoso
        Mingas
        Moita
        Moniz
        Morango
        Napoleao
        Narciso
        Natividade
        Nazare
        Nela
        Neto
        Novato
        Nsambu
        Odebrecht
        Ortet
        Paim
        Paixao
        Palanca
        Palha
        Panzo
        Passi
        Pitra
        Praia
        Prata
        Principe
        Queiros
        Quintas
        Rato
        Robalo
        Rufino
        Ruivo
        Sabino
        Sardinha
        Semedo
        Serafim
        Simba
        Suco
        Suzana
        Swagger
        Tabita
        Tati
        Teca
        Tigre
        Tuta
        Baltazar
        Barnabe
        Bartolomeu
        Batalha
        Benge
        Benza
        Bernado
        Vado
        Valente
        Valentim
        Valter
        Vania
        Veloso
        Venancio
        Vica
        Vigario
        Vika
        Viriato
        Weza
        Yola
        Yuri
        Zacarias
        Brilhante
        Buco
        Buela
        Bunga
        Cabrita
        Bungo
        Caly
        Candeias
        Capela
        Carina
        Cassio
        Cassola
        Castigo
        Cavaleiro
        Celestino
        Cerca
        Cisco
        Coimbra
        Coimbra
        Constantino
        Craveiro
        Cubana
        Cubano
        Custodio
        Danny)
  end

  def self.female_brazilian_first_names
    %w(
        Gabriela
        Fernanda
        Júlia
        Beatriz
        Mariana
        Larissa
        camila
        leticia
        Juliana
        Margarida
        Marinela
        Natália
        Thais
        vitoria
        Rafaela
        Luana
        Bruna
        Isabela
        Carolina
        Aline
        giovanna
        Victória
        daniela
        Marcela
        Andressa
        Eduarda
        Raissa
        Nathalia
        Nayara
        lara
        Cristina
        Michele
        Yasmin
        Flávia
        clara
        viviane
        Patrícia
        Gabi
        camilla
        marcella
        Renata
        Marcia
        Adriana
        Tania
        Sonia
        Lucia
        Luciana)
  end
end