class SearchableNames
  def self.last_names
    %w(Almeida
      Alsina
      Alves
      Amado
      Andrade
      Azevedo
      Baia
      Barbosa
      Braga
      Cabreira
      Caetano
      Cardoso
      Carvalho
      Coelho
      Conceicao
      Cunha
      DaCosta
      DaSilva
      D'Almeida
      DeCarvalho
      DeFreitas
      DeOliveira
      DePaulo
      DeSousa
      DeSouza
      DosSantos
      Freitas
      Guimaraes
      Joao
      Magalhaes
      Martins
      Medeiros
      Morais
      Moreira
      Nascimento
      Nogueira
      Oliveira
      Paixao
      Pereira
      Pinheiro
      Pinto
      Ribeiro
      Rocha
      Salgueiro
      Sardinha
      Simoes
      Siqueira
      Souza
      Teixeira
      Vieira)
  end
end